// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scriptorium.Mtg.Api.DatabaseContext;

#nullable disable

namespace Scriptorium.Mtg.Api.Migrations
{
    [DbContext(typeof(MtgDbContext))]
    [Migration("20260911131525_ContributionSchema")]
    partial class ContributionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Scriptorium.Mtg.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Colors")
                        .HasColumnType("int");

                    b.Property<int>("ColorsIdentity")
                        .HasColumnType("int");

                    b.Property<int>("ColorsIndicator")
                        .HasColumnType("int");

                    b.Property<string>("HandModifier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.PrimitiveCollection<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LifeModifier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Loyalty")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("ManaValue")
                        .HasColumnType("float");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.PrimitiveCollection<string>("ProducedMana")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Toughness")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.CardFace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Colors")
                        .HasColumnType("int");

                    b.Property<int>("ColorsIndicator")
                        .HasColumnType("int");

                    b.Property<int?>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Loyalty")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("ManaValue")
                        .HasColumnType("float");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Toughness")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardFaces");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.CardName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardNames");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.CardSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.PrimitiveCollection<string>("NormalImagesUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("SmallImagesUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("SetId");

                    b.ToTable("CardSets");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.CardSetFace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("ArtistsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CardSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardSetId");

                    b.ToTable("CardSetFaces");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.CardSetFaceFlavor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardSetFaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FlavorName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FlavorText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("CardSetFaceId");

                    b.ToTable("CardSetFaceFlavor");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.CardText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardTexts");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.CardTypeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardTypelines");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.RelatedCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("RelatedCards");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "No color",
                            Name = "None"
                        },
                        new
                        {
                            Id = 2,
                            Description = "White",
                            Name = "W"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Blue",
                            Name = "U"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Black",
                            Name = "B"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Red",
                            Name = "R"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Green",
                            Name = "G"
                        });
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Contribution.TranslationRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("PreviousValue")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("CardId", "Language", "CreatedAt");

                    b.HasIndex("TargetType", "TargetId", "CreatedAt");

                    b.ToTable("TranslationRevisions");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Contribution.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Ruling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("Rulings");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Set", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Block")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BlockCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ParentSetCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Typeline.Subtype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TypeCard")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Subtypes");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Typeline.SubtypeLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("SubtypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SubtypeLanguages");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Typeline.Supertype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Supertypes");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Typeline.SupertypeLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("SupertypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SupertypeLanguages");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Typeline.Type", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937"),
                            DefaultName = "Card"
                        });
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Typeline.TypeLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TypeLanguages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("669367c3-ba1f-4b27-abe8-b0ca40b13d5a"),
                            Language = "en",
                            Name = "Card",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("bad689b4-49a5-4464-8257-eac72029b0dd"),
                            Language = "es",
                            Name = "Carta",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("f5a5239c-8d67-4e85-9419-e640a666acbc"),
                            Language = "fr",
                            Name = "Carte",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("5346476c-2b05-4360-9705-54aa0376ab58"),
                            Language = "de",
                            Name = "Karte",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("8b2ec9e8-e20e-455b-8b17-a1b03b259290"),
                            Language = "it",
                            Name = "Carta",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("c070e592-089a-4e4e-b1a8-93ab4c09d984"),
                            Language = "pt",
                            Name = "Card",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("66dd5abf-cf59-41f0-ae3f-5d52190469ab"),
                            Language = "ja",
                            Name = "カード",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("5eeb72fe-2186-4954-add5-e610d6dc5ce2"),
                            Language = "ko",
                            Name = "카드",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("c53a1ccd-5452-4c78-8029-746aa7f44635"),
                            Language = "ru",
                            Name = "карту",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("a6999ee9-7fa1-4d05-87fe-020859e07fb7"),
                            Language = "zhs",
                            Name = "牌",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("4284fd77-bfa0-44c1-9941-5cfd4f2c0b74"),
                            Language = "zht",
                            Name = "牌",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        });
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.CardFace", b =>
                {
                    b.HasOne("Scriptorium.Mtg.Models.Card.Card", null)
                        .WithMany("CardFaces")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.CardName", b =>
                {
                    b.HasOne("Scriptorium.Mtg.Models.Card.Card", null)
                        .WithMany("CardNames")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.CardSet", b =>
                {
                    b.HasOne("Scriptorium.Mtg.Models.Card.Card", null)
                        .WithMany("CardSets")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scriptorium.Mtg.Models.Set", "Set")
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.CardSetFace", b =>
                {
                    b.HasOne("Scriptorium.Mtg.Models.Card.CardSet", null)
                        .WithMany("CardSetFaces")
                        .HasForeignKey("CardSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.CardSetFaceFlavor", b =>
                {
                    b.HasOne("Scriptorium.Mtg.Models.Card.CardSetFace", null)
                        .WithMany("Flavors")
                        .HasForeignKey("CardSetFaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.CardText", b =>
                {
                    b.HasOne("Scriptorium.Mtg.Models.Card.Card", null)
                        .WithMany("CardTexts")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.CardTypeline", b =>
                {
                    b.HasOne("Scriptorium.Mtg.Models.Card.Card", null)
                        .WithMany("CardTypelines")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.RelatedCard", b =>
                {
                    b.HasOne("Scriptorium.Mtg.Models.Card.Card", null)
                        .WithMany("RelatedCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Contribution.TranslationRevision", b =>
                {
                    b.HasOne("Scriptorium.Mtg.Models.Contribution.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Ruling", b =>
                {
                    b.HasOne("Scriptorium.Mtg.Models.Card.Card", null)
                        .WithMany("Rulings")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.Card", b =>
                {
                    b.Navigation("CardFaces");

                    b.Navigation("CardNames");

                    b.Navigation("CardSets");

                    b.Navigation("CardTexts");

                    b.Navigation("CardTypelines");

                    b.Navigation("RelatedCards");

                    b.Navigation("Rulings");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.CardSet", b =>
                {
                    b.Navigation("CardSetFaces");
                });

            modelBuilder.Entity("Scriptorium.Mtg.Models.Card.CardSetFace", b =>
                {
                    b.Navigation("Flavors");
                });
#pragma warning restore 612, 618
        }
    }
}
