// <auto-generated />
using System;
using MTG.Api.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTG.Api.Migrations
{
    [DbContext(typeof(MtgDbContext))]
    partial class MtgDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MTG.Database.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Colors")
                        .HasColumnType("int");

                    b.Property<int>("ColorsIdentity")
                        .HasColumnType("int");

                    b.Property<int>("ColorsIndicator")
                        .HasColumnType("int");

                    b.Property<string>("HandModifier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LifeModifier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Loyalty")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("ManaValue")
                        .HasColumnType("float");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProducedMana")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Toughness")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardFace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Colors")
                        .HasColumnType("int");

                    b.Property<int>("ColorsIndicator")
                        .HasColumnType("int");

                    b.Property<int?>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Loyalty")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("ManaValue")
                        .HasColumnType("float");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Toughness")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardFaces");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardNames");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("SetId");

                    b.ToTable("CardSets");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSetFace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtistsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CardSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardSetId");

                    b.ToTable("CardSetFaces");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSetFaceFlavor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardSetFaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FlavorName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FlavorText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("CardSetFaceId");

                    b.ToTable("CardSetFaceFlavor");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardTexts");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardTypeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardTypelines");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.RelatedCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("RelatedCards");
                });

            modelBuilder.Entity("MTG.Database.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "No color",
                            Name = "None"
                        },
                        new
                        {
                            Id = 2,
                            Description = "White",
                            Name = "W"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Blue",
                            Name = "U"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Black",
                            Name = "B"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Red",
                            Name = "R"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Green",
                            Name = "G"
                        });
                });

            modelBuilder.Entity("MTG.Database.Models.Ruling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("Rulings");
                });

            modelBuilder.Entity("MTG.Database.Models.Set", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Block")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BlockCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ParentSetCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.Subtype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TypeCard")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Subtypes");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.SubtypeLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("SubtypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SubtypeLanguages");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.Supertype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Supertypes");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.SupertypeLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("SupertypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SupertypeLanguages");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.Type", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937"),
                            DefaultName = "Card"
                        });
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.TypeLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TypeLanguages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("272c1d99-f114-4cf1-94ba-5e16fd8b8c9a"),
                            Language = "en",
                            Name = "Card",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("44893044-8aa9-4292-8e6e-cb0ddd83a9df"),
                            Language = "es",
                            Name = "Carta",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("d41918b1-f330-4110-8dc3-d9fdbc58c5e3"),
                            Language = "fr",
                            Name = "Carte",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("f655ecff-6d35-440a-b4d0-4b874172eb2f"),
                            Language = "de",
                            Name = "Karte",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("a57f1fc2-37c4-46b1-86fb-60b1f96a781c"),
                            Language = "it",
                            Name = "Carta",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("caf94bfa-5a3b-4a3e-bf06-9e9d0d9379a3"),
                            Language = "pt",
                            Name = "Card",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("05aa7d5c-9d3e-4a34-a864-61b8aca1d6db"),
                            Language = "ja",
                            Name = "カード",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("a2f9f429-b828-47e4-af5a-06cb51b33bd1"),
                            Language = "ko",
                            Name = "카드",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("4c89c29f-729d-49fb-8161-6a855d1cd9be"),
                            Language = "ru",
                            Name = "карту",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("55816bc7-d400-4e6c-a874-9cf1fd1368c6"),
                            Language = "zhs",
                            Name = "牌",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("7b34864b-c011-492f-8eeb-4cafe448ffc9"),
                            Language = "zht",
                            Name = "牌",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        });
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardFace", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("CardFaces")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardName", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("CardNames")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSet", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("CardSets")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTG.Database.Models.Set", "Set")
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSetFace", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.CardSet", null)
                        .WithMany("CardSetFaces")
                        .HasForeignKey("CardSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSetFaceFlavor", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.CardSetFace", null)
                        .WithMany("Flavors")
                        .HasForeignKey("CardSetFaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardText", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("CardTexts")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardTypeline", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("CardTypelines")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.RelatedCard", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("RelatedCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Ruling", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("Rulings")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.Card", b =>
                {
                    b.Navigation("CardFaces");

                    b.Navigation("CardNames");

                    b.Navigation("CardSets");

                    b.Navigation("CardTexts");

                    b.Navigation("CardTypelines");

                    b.Navigation("RelatedCards");

                    b.Navigation("Rulings");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSet", b =>
                {
                    b.Navigation("CardSetFaces");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSetFace", b =>
                {
                    b.Navigation("Flavors");
                });
#pragma warning restore 612, 618
        }
    }
}
