// <auto-generated />
using System;
using MTG.Api.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTG.Api.Migrations
{
    [DbContext(typeof(MTGDbContext))]
    partial class MTGDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MTG.Database.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Colors")
                        .HasColumnType("int");

                    b.Property<int>("ColorsIdentity")
                        .HasColumnType("int");

                    b.Property<int>("ColorsIndicator")
                        .HasColumnType("int");

                    b.Property<string>("HandModifier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LifeModifier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Loyalty")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("ManaValue")
                        .HasColumnType("float");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProducedMana")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Toughness")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardFace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Colors")
                        .HasColumnType("int");

                    b.Property<int>("ColorsIndicator")
                        .HasColumnType("int");

                    b.Property<int?>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Loyalty")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("ManaValue")
                        .HasColumnType("float");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Toughness")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CardId", "FaceId");

                    b.ToTable("CardFaces");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CardId", "Language", "FaceId");

                    b.ToTable("CardNames");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("SetId");

                    b.ToTable("CardSets");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSetFace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtistsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CardSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("FlavorName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardSetId", "FaceId");

                    b.ToTable("CardSetFaces");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardId", "Language", "FaceId");

                    b.ToTable("CardTexts");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardTypeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CardId", "Language", "FaceId");

                    b.ToTable("CardTypelines");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.RelatedCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("RelatedCards");
                });

            modelBuilder.Entity("MTG.Database.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "No color",
                            Name = "None"
                        },
                        new
                        {
                            Id = 2,
                            Description = "White",
                            Name = "W"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Blue",
                            Name = "U"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Black",
                            Name = "B"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Red",
                            Name = "R"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Green",
                            Name = "G"
                        });
                });

            modelBuilder.Entity("MTG.Database.Models.Set", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ParentSetCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.Subtype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TypeCard")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Subtypes");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.SubtypeLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("SubtypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubtypeId");

                    b.ToTable("SubtypeLanguages");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.Supertype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Supertypes");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.SupertypeLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("SupertypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SupertypeId");

                    b.ToTable("SupertypeLanguages");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.Type", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937"),
                            DefaultName = "Card"
                        });
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.TypeLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("TypeLanguages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5b9d8c3-c2b8-4e94-835e-28642fb3c6ed"),
                            Language = "en",
                            Name = "Card",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("7c7d9ab5-51d5-424e-a4ab-8ff948d864f4"),
                            Language = "es",
                            Name = "Carta",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("947e6e87-5992-40a0-af6a-f4eb24483e91"),
                            Language = "fr",
                            Name = "Carte",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("4bb44a1f-0ccb-4745-976c-695129b17c11"),
                            Language = "de",
                            Name = "Karte",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("b08972a3-28fa-44c2-872b-e95a125861d2"),
                            Language = "it",
                            Name = "Carta",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("5798dd97-dde5-404b-85e5-65a8e83bc712"),
                            Language = "pt",
                            Name = "Card",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("d4ec3d26-ed9d-4b22-a3d2-bdcc84408171"),
                            Language = "ja",
                            Name = "カード",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("857cd2ed-6356-4341-9b1b-5fe51cfdb3b9"),
                            Language = "ko",
                            Name = "카드",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("3d89d1ea-9aaf-4a53-a95b-632a808e5f53"),
                            Language = "ru",
                            Name = "карту",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("d29b77d1-7fcd-4b55-8a3e-18b94c70e607"),
                            Language = "zhs",
                            Name = "牌",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("06a47464-b6b9-4a14-86e8-363ddfed3b40"),
                            Language = "zht",
                            Name = "牌",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        });
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardFace", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("CardFaces")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardName", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("CardNames")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSet", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("CardSets")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTG.Database.Models.Set", "Set")
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSetFace", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.CardSet", null)
                        .WithMany("CardSetFaces")
                        .HasForeignKey("CardSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardText", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("CardTexts")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardTypeline", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("CardTypelines")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.RelatedCard", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("RelatedCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.SubtypeLanguage", b =>
                {
                    b.HasOne("MTG.Database.Models.Typeline.Subtype", "Subtype")
                        .WithMany()
                        .HasForeignKey("SubtypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subtype");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.SupertypeLanguage", b =>
                {
                    b.HasOne("MTG.Database.Models.Typeline.Supertype", "Supertype")
                        .WithMany()
                        .HasForeignKey("SupertypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supertype");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.TypeLanguage", b =>
                {
                    b.HasOne("MTG.Database.Models.Typeline.Type", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.Card", b =>
                {
                    b.Navigation("CardFaces");

                    b.Navigation("CardNames");

                    b.Navigation("CardSets");

                    b.Navigation("CardTexts");

                    b.Navigation("CardTypelines");

                    b.Navigation("RelatedCards");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSet", b =>
                {
                    b.Navigation("CardSetFaces");
                });
#pragma warning restore 612, 618
        }
    }
}
