// <auto-generated />
using System;
using MTG.Api.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTG.Api.Migrations
{
    [DbContext(typeof(MtgDbContext))]
    [Migration("20260910230320_Net10Upgrade")]
    partial class Net10Upgrade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MTG.Database.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Colors")
                        .HasColumnType("int");

                    b.Property<int>("ColorsIdentity")
                        .HasColumnType("int");

                    b.Property<int>("ColorsIndicator")
                        .HasColumnType("int");

                    b.Property<string>("HandModifier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.PrimitiveCollection<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LifeModifier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Loyalty")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("ManaValue")
                        .HasColumnType("float");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.PrimitiveCollection<string>("ProducedMana")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Toughness")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardFace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Colors")
                        .HasColumnType("int");

                    b.Property<int>("ColorsIndicator")
                        .HasColumnType("int");

                    b.Property<int?>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Loyalty")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("ManaValue")
                        .HasColumnType("float");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Toughness")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardFaces");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardNames");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.PrimitiveCollection<string>("NormalImagesUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("SmallImagesUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("SetId");

                    b.ToTable("CardSets");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSetFace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("ArtistsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CardSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardSetId");

                    b.ToTable("CardSetFaces");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSetFaceFlavor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardSetFaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FlavorName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FlavorText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("CardSetFaceId");

                    b.ToTable("CardSetFaceFlavor");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardTexts");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardTypeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FaceId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardTypelines");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.RelatedCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("RelatedCards");
                });

            modelBuilder.Entity("MTG.Database.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "No color",
                            Name = "None"
                        },
                        new
                        {
                            Id = 2,
                            Description = "White",
                            Name = "W"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Blue",
                            Name = "U"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Black",
                            Name = "B"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Red",
                            Name = "R"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Green",
                            Name = "G"
                        });
                });

            modelBuilder.Entity("MTG.Database.Models.Ruling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("Rulings");
                });

            modelBuilder.Entity("MTG.Database.Models.Set", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Block")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BlockCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ParentSetCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.Subtype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TypeCard")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Subtypes");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.SubtypeLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("SubtypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SubtypeLanguages");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.Supertype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Supertypes");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.SupertypeLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("SupertypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SupertypeLanguages");
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.Type", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937"),
                            DefaultName = "Card"
                        });
                });

            modelBuilder.Entity("MTG.Database.Models.Typeline.TypeLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TypeLanguages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be0dda5f-379e-4d6d-ab52-b01f3aaa55bc"),
                            Language = "en",
                            Name = "Card",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("2d58c34b-27f4-4506-95be-2404c138d535"),
                            Language = "es",
                            Name = "Carta",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("30015bd7-e452-43fd-bae2-c751c6ed23c3"),
                            Language = "fr",
                            Name = "Carte",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("5d0cf57e-2dbf-4133-b679-15a85d7bc8ce"),
                            Language = "de",
                            Name = "Karte",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("a0ec02ac-825c-42d9-8845-2f1f01922dc5"),
                            Language = "it",
                            Name = "Carta",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("79972c36-450b-4966-8d9e-f6c217689c74"),
                            Language = "pt",
                            Name = "Card",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("3449fd96-0f9b-44c0-bbf4-8710b8ab48ec"),
                            Language = "ja",
                            Name = "カード",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("3a2733f1-994e-46b0-bfdf-09f332ff3daa"),
                            Language = "ko",
                            Name = "카드",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("052ab03b-29fa-46af-9ecd-ddfe33413c5b"),
                            Language = "ru",
                            Name = "карту",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("1f7c43c1-77ec-458b-b483-432946da2565"),
                            Language = "zhs",
                            Name = "牌",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        },
                        new
                        {
                            Id = new Guid("ce3144d2-e168-43ee-916b-af91982b6fd2"),
                            Language = "zht",
                            Name = "牌",
                            TypeId = new Guid("18943286-deb5-4d81-b089-6cc4bc2b6937")
                        });
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardFace", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("CardFaces")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardName", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("CardNames")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSet", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("CardSets")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTG.Database.Models.Set", "Set")
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSetFace", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.CardSet", null)
                        .WithMany("CardSetFaces")
                        .HasForeignKey("CardSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSetFaceFlavor", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.CardSetFace", null)
                        .WithMany("Flavors")
                        .HasForeignKey("CardSetFaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardText", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("CardTexts")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardTypeline", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("CardTypelines")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.RelatedCard", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("RelatedCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Ruling", b =>
                {
                    b.HasOne("MTG.Database.Models.Card.Card", null)
                        .WithMany("Rulings")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTG.Database.Models.Card.Card", b =>
                {
                    b.Navigation("CardFaces");

                    b.Navigation("CardNames");

                    b.Navigation("CardSets");

                    b.Navigation("CardTexts");

                    b.Navigation("CardTypelines");

                    b.Navigation("RelatedCards");

                    b.Navigation("Rulings");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSet", b =>
                {
                    b.Navigation("CardSetFaces");
                });

            modelBuilder.Entity("MTG.Database.Models.Card.CardSetFace", b =>
                {
                    b.Navigation("Flavors");
                });
#pragma warning restore 612, 618
        }
    }
}
